---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Services:

    - Pi-Hole Admin:
        href: https://subiaco-node1/admin
        icon: pi-hole
        description: DNS/DCHP

    - FireFly:
        href: http://subiaco-node1:99
        icon: si-fireflyiii
        description: Budgeting

