---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
title: Subiaco
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
iconLibraries:
  - mdi
  - simple-icons  # optional, for brand logos like github, docker, etc.

