---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- greeting:
  - text_size: 4x1
  - text: Welcome to Subiaco

- search:
    provider: duckduckgo
    target: _blank

- resources:
    cpu: true
    memory: true
